version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ../:/blackstar_blog_engine
    ports:
      - "5005:80"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=blog_db
    ports:
      - "54321:5432"
