version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=test1
    volumes:
      - ../:/code
    ports:
      - "5005:80"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=test123
    ports:
      - "54321:5432"
