name: Deployment

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build project container
        run: docker-compose -f .devcontainer/docker-compose.yml up -d

      - name: Static code analysis
        run: |
          docker-compose exec flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          docker-compose exec flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        run: docker-compose exec pytest tests/unit

      - name: Run integration tests
        run: docker-compose exec pytest tests/integration

      - name: Run e2e tests
        run: docker-compose exec pytest tests/e2e
